# Generated by Django 3.0.6 on 2020-05-14 20:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('gi', models.CharField(max_length=200)),
                ('serve', models.CharField(max_length=200)),
                ('carb_per_serve', models.CharField(max_length=200)),
                ('gl', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
